# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestWarhouses():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_warhouses(self):
        self.driver.get("http://dev.project.ex2.team:6969/purchase/requisitions-board")
        self.driver.find_element(By.CSS_SELECTOR, "rect:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_menu__element_59rwn_31:nth-child(7) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_blue_oj2b3_117 > div").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").send_keys(
            "Test Warehouse")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(1) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(1) > input").send_keys(
            "1@1.com")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(2) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(2) > input").send_keys(
            "Anton")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_row_13jvn_76:nth-child(6) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_row_13jvn_76:nth-child(6) input").send_keys("Address")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_blue_oj2b3_117 > div").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").send_keys(
            "Test Edit Warehouse")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(1) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(1) > input").send_keys(
            "2@2.com")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_row_13jvn_76:nth-child(6) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_row_13jvn_76:nth-child(6) input").send_keys("address")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_10okp_1:nth-child(3) .\\_wrapper_oj2b3_1:nth-child(1) div:nth-child(2) > svg").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(3) > .\\_wrapper_170o3_1:nth-child(1) > input").send_keys(
            "Test Edit/Delete Warehouse")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(2) > input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_13jvn_76:nth-child(4) > .\\_wrapper_170o3_1:nth-child(2) > input").send_keys(
            "3@3.com")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242 > div").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".\\_row_10okp_1:nth-child(3) .\\_lightGreyToRed_oj2b3_347 > .\\_prefixImg_oj2b3_26").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_lightGreen_oj2b3_242 > div").click()

